# Cargo.toml
[package]
name = "solutiont3"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
gag = "1.0.0"  # 用于捕获标准输出

[[test]]
name = "tests"
path = "src/tests.rs"